# org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dsun.zip.disableMemoryMapping=true

# for debug
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dsun.zip.disableMemoryMapping=true
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=true
